### ISSUE TITLE
Thorim HM P2 Chain Lightning range check incorrect?

### ISSUE THREAD

**Issue by dharich** [BigWigsMods/BigWigs_WrathOfTheLichKing#17]
Phase 2's Chain Lightning seems to have an 8 yards range but the range check opens up with 5 yards. Wowhead's guide recommends 10 yards and so does DBM. Other sources list the spell's range as 8 yards

**Comment by funkydude** [comment]
Thanks for reporting this, please keep reporting any other issues you encounter in Ulduar. New release is out with a fix.
