### ISSUE TITLE
Wiped on "Kel'Thuzad" announcement

### ISSUE THREAD

**Issue by Vachon8449** [BigWigsMods/BigWigs_WrathOfTheLichKing#22]
## Describe the problem
I've been running alts through Naxxramas  Recently, today, maybe started yesterday (today is July 24, 2023) I started getting a message in chat that I wiped on Kel'Thuzad when, in fact, I didn't wipe, but killed him in one shot. Most of my alts are level 70. Even those that are level 60 kill him in three shots. None of my alts take any damage from him.  

### What steps will reproduce the problem?

1.  I'm not sure what steps will reproduce the problem. It has happened on a variety of classes, mage, paladin, hunter, shaman, priest.
2.  I would think just run though the instance. I kill everything for T-mog as well as the Corruptor's Scourgestones. 
3.  I would think that should reproduce the problem, but I don't really know.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![WoWScrnShot_072423_233603](https://github.com/BigWigsMods/BigWigs/assets/49286054/11941c83-b9e5-41bf-b636-41125a09779e)

### What version of BigWigs are you using? (Stating 'latest' is not useful)
I'm not sure where it tells me what version I'm running. At the bottom of the BigWigs window it says, "you are running an official release of BigWigs 288 (af97c12) Is that the version? Which is shown in the screenshot.

### Do you have an error log of what happened?
I didn't get an error, just the message in the chat window. Which is shown in the screenshot as well.

### Any additional information? (example: WoW language if not English)
Update: I sent another alt though, this time watching the chat window. It gave me the announcement "[Kagryn] has earned the achievement [Kel'Thuzad's Defeat (25 player)]! when I killed him. I stuck around, which I normally do to kill the additional adds that come at me after he's down, and after getting 4 messages "A Guardian of Icecrown enters the fight!" and then killing each them. That's when I get the announcement in chat 
"BigWigs: Wiped on 'Kel'Thuzad' after 5 min 1 Sec. 
"BigWigs: Health: Kel'Thuzad (3.9%)"
Except, he's dead. 
I tried attaching an updated screenshot, but I guess we can only attach one per message. If you need to see them, I have them for the two messages about earning the achievement and then him not being dead and wiping.

**Comment by funkydude** [comment]
As far as I can see, this has been broken since late last year, thanks for reporting!
