### ISSUE TITLE
LK & blood prince council issues

### ISSUE THREAD

**Issue by lordblackadder** [BigWigsMods/BigWigs_WrathOfTheLichKing#28]
BW v293.1 and BW_WotLK v10.1.8

**LK:** shows a warning for Necrotic Plague
```
1x BigWigs: Found spell 'Necrotic Plague' using id 70338 on 4, tell the authors!
[string "@BigWigs_Core/BossPrototype_Classic.lua"]:1512: in function `UnitDebuff'
[string "@BigWigs_WrathOfTheLichKing/Citadel/LichKing.lua"]:209: in function `func'
```

**BPC:** The health swap timer bar gets stuck on screen after a wipe
![image](https://github.com/BigWigsMods/BigWigs_WrathOfTheLichKing/assets/12127284/e289ccf2-dfb6-456c-b85b-4eae7abdb417)

The issue with timer bars being stuck on screen happens with some other bosses too (including 5man). Not sure if it's an issue with BW and not the WotLK module necessarily. I will try to keep track of the bosses it occurs whenever I see it. I only started noticing it after updating to the shared BW version (from 48-classic-wrath to 290+)

**Comment by funkydude** [comment]
With regards to the council issue, I gather this only happens on a wipe, not a kill. I'm assuming you're releasing straight away on a wipe, can you try to wait 20 seconds before releasing to see if the bar clears?

**Comment by lordblackadder** [comment]
It happens on a wipe but it doesn't have to do with releasing. I ressed with a soulstone after the attempt in the screenshot so I didn't miss any event
