### ISSUE TITLE
No timers on first encounter with Deathbringer Saurfang

### ISSUE THREAD

**Issue by erreip-1** [BigWigsMods/BigWigs_WrathOfTheLichKing#29]
BigWigs timers are not loading on first pull of Deathbringer Saurfang (tested on 25hm).
It is loading properly on subsequent pulls in case of wipe / reset.

**Comment by funkydude** [comment]
We need a log from the Transcriptor addon in order to debug this further.

**Comment by erreip-1** [comment]
[Transcriptor.txt](https://github.com/BigWigsMods/BigWigs_WrathOfTheLichKing/files/13199050/Transcriptor.txt)

I forgot to stop after the boss so there might be a little more than needed.
Tested tonight in 10hm.

**Comment by funkydude** [comment]
Unfortunately I could never reproduce this, even all the streams I watched it worked first time.

The log was useful but didn't reveal what the issue could have been.

I've made a change though to hopefully resolve the issue. It won't fix the pre-combat timer not showing, but it should at least fix the boss timers.

Let us know what effect it has!
