### ISSUE TITLE
Blood prince council health swap bar swap gets stuck in screen

### ISSUE THREAD

**Issue by lordblackadder** [BigWigsMods/BigWigs_WrathOfTheLichKing#30]
I'm opening a new ticket for the BPC issue described in https://github.com/BigWigsMods/BigWigs_WrathOfTheLichKing/issues/28

I've confirmed this week that this happens every time there is a wipe (no release spirit involved, not sure if it does **not** happen if you release). The issue does not occur if you kill the boss.

**Comment by lordblackadder** [comment]
Good news; I have more information about what's happening :) Wiping properly gets rid of the bars, however, when the princes respawn there is a small RP sequence and that triggers the swap timer bar to appear and then it gets stuck.

I've captured it in video [here](https://www.youtube.com/watch?v=skTQvdet_0k)
As well as used Transcriptor for the fight which I've attached (renamed to txt to allow me to attach)
[Transcriptor.txt](https://github.com/BigWigsMods/BigWigs_WrathOfTheLichKing/files/13196892/Transcriptor.txt)

In my video it's already stuck on screen when it starts, but it will disappear and reappear after the wipe too

**Comment by funkydude** [comment]
That makes a lot more sense, thanks!
