### ISSUE TITLE
Error on Hodir

### ISSUE THREAD

**Issue by Xerus2** [BigWigsMods/BigWigs_WrathOfTheLichKing#6]
BigWigs: Found spell "Biting Cold" using id 62039 on 14, tell the authors!

**Comment by Talimar** [comment]
Error is still there:

2x Found spell 'Biting Cold' using id 62039 on 24, tell the authors!
BigWigs_Core\BossPrototype.lua:1142: in function `UnitDebuff'
...eBigWigs_WrathOfTheLichKing\Ulduar\Hodir.lua:104: in function `?'
BigWigs_Core\BossPrototype.lua:528: in function <BigWigs_Core\BossPrototype.lua:523>

Locals:
InCombatSkipped
