### ISSUE TITLE
Found LUA Error for Thorim in Ulduar

### ISSUE THREAD

**Issue by the-quality** [BigWigsMods/BigWigs_WrathOfTheLichKing#8]
`1x BigWigs_WrathOfTheLichKing\Ulduar\Thorim.lua:173: bad argument #1 to '(for generator)' (table expected, got nil)
[string "=[C]"]: in function `(for generator)'
[string "@BigWigs_WrathOfTheLichKing\Ulduar\Thorim.lua"]:173: in function `StageTwo'
[string "@BigWigs_WrathOfTheLichKing\Ulduar\Thorim.lua"]:190: in function `?'
[string "@BigWigs_Core\Core.lua"]:59: in function <BigWigs_Core\Core.lua:54>

Locals:
Skipped (In Encounter)`

maybe you can finx it

thx

**Comment by funkydude** [comment]
Thanks for reporting this. It's now fixed.
